# Generated by Django 4.1.8 on 2023-09-13 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='canteen',
            fields=[
                ('canteen_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=12, null=True)),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=12, null=True)),
                ('cust', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('canteen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CafeApp.canteen')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField()),
                ('items', models.ManyToManyField(default=None, related_name='order_item', to='CafeApp.items')),
                ('order_cust', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CafeApp.customer')),
            ],
        ),
    ]
