# Generated by Django 4.2.5 on 2023-09-14 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0002_alter_canteen_owner_alter_customer_cust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteen',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CafeApp.profile'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CafeApp.profile'),
        ),
    ]
